run qemu-kvm if the box has it

diff --git a/system/template-qemu/qemu-start-node b/system/template-qemu/qemu-start-node
--- a/system/template-qemu/qemu-start-node
+++ b/system/template-qemu/qemu-start-node
@@ -46,11 +46,16 @@ function is_64bits () {
 
 # the launcher, depending on target arch
 # make sure to check qemu-kill-node for consistency
-case $TARGET_ARCH in
-    i386)		QEMU=qemu ; ARGS="" ;;
-    x86_64)		QEMU=qemu-system-x86_64 ; if is_64bits; then ARGS="-no-kqemu"; else ARGS=""; fi ;;
-    *)			echo "Cannot handle TARGET_ARCH=$TARGET_ARCH"; exit 1 ;;
-esac
+has_kvm=$(type -p qemu-kvm)
+if [ -n "has_kvm" ] ; then
+    QEMU="qemu-kvm" ; ARGS=""
+else
+    case $TARGET_ARCH in
+	i386)		QEMU=qemu ; ARGS="" ;;
+	x86_64)		QEMU=qemu-system-x86_64 ; if is_64bits; then ARGS="-no-kqemu"; else ARGS=""; fi ;;
+	*)			echo "Cannot handle TARGET_ARCH=$TARGET_ARCH"; exit 1 ;;
+    esac
+fi
 
 echo "Running $COMMAND in $(pwd)"
 echo "Starting at $(date)"
