*Cosmetic for getting the right MAC @ for the emulated node./*No need anymore to create the hda disk image in the env-qemu script.

diff --git a/system/template-Qemu/start-qemu-node b/system/template-Qemu/start-qemu-node
--- a/system/template-Qemu/start-qemu-node
+++ b/system/template-Qemu/start-qemu-node
@@ -1,35 +1,44 @@
 #!/bin/bash
 
-#Default Value
-set $(pwd)
-NODE_DIR=$1
-shift $(($# -1))
-CDROM_IMG=${NODE_DIR}/boot_file.iso
-HDA=$NODE_DIR/hda_5.raw;	
-
-#Getting the MAC address
-if [ ! -e "$NODE_DIR/MAC" ];then
+#Getting the MAC address and the right path
+MACPATH=~/$1/MAC
+if [ ! -e ${MACPATH} ];then
     echo "File for MAC Address not found"
     exit 1
 fi
-set $(cat $NODE_DIR/MAC)
+set $(cat ${MACPATH})
 MACADDR=$1
+NODE_DIR=$2
 shift $(($# -1))
+
+#default Value
+CDROM_IMG=~/${NODE_DIR}/boot_file.iso
+SCRIPT=~/${NODE_DIR}/qemu-ifup
+FILENAME=hda_5.raw
+HDA=~/${NODE_DIR}/${FILENAME};	
 
 # qemu parameters
 RAM=320;
-TAP="tap,script=${NODE_DIR}/qemu-ifup";
-echo $NODE_DIR
+TAP="tap,script=$SCRIPT";
 #check for the creation of new HDA
 if [ -e "$HDA" ]; then
     echo "Disk already existing removing  it..."
     rm -rf $HDA
 fi
-qemu-img create $HDA 5G
+#Creating new HDA
+echo "Creating hard disk for Qemu install under $HDA"
+set $(qemu-img create $FILENAME 5G)
+if [ -z "$1" ];then
+	echo "Can't Create disk image..."
+	exit 1
+fi
+shift $(($# - 1))
+#unfortunately :-( qemu-img don't accept a path for image but only filename
+mv ~/$FILENAME $HDA
 echo "New $HDA is created..."
 
 #Command for running the Qemu Emulator
-ARGS="-boot d -cdrom ${CDROM_IMG} -hda ${HDA} -m ${RAM} -net nic,macaddr=${MACADDR} -net $TAP ";
+ARGS="-boot d -cdrom ${CDROM_IMG} -hda ${HDA} -m ${RAM} -net nic,macaddr=${MACADDR} -net $TAP -no-kqemu";
 echo "Executing qemu $ARGS";
 qemu $ARGS
 
